### ISSUE TITLE
Wrong length zero bytes for UTF-8 encoding strings

### ISSUE THREAD

**Issue by edementiev** [CrunchyBagel/OutcastID3#3]
Data+String.swift
in case when comment have encoding .utf8 and we looking for zero bytes end of string we must wait ONE zero byte not two

two zero bytes only for UTF16

// unicode strings are terminated by \0\0, while latin terminated by \0
your comment is wrong only utf16 strinds are termonated by \0\0

http://id3.org/id3v2.4.0-structure
Frames that allow different types of text encoding contains a text
   encoding description byte. Possible encodings:

     $00   ISO-8859-1 [ISO-8859-1]. Terminated with $00.
     $01   UTF-16 [UTF-16] encoded Unicode [UNICODE] with BOM. All
           strings in the same frame SHALL have the same byteorder.
           Terminated with $00 00.
     $02   UTF-16BE [UTF-16] encoded Unicode [UNICODE] without BOM.
           Terminated with $00 00.
     $03   UTF-8 [UTF-8] encoded Unicode [UNICODE]. Terminated with $00.

**Comment by HendX** [comment]
Do you know if this is for all versions, or just for 2.4? In 2.3, it just mentions "unicode" but doesn't differentiate between UTF-8 and UTF-16.

    All numeric strings and URLs [URL] are always encoded as ISO-8859-1. Terminated strings are terminated with $00 if encoded with ISO-8859-1 and $00 00 if encoded as unicode.

http://id3.org/d3v2.3.0

**Comment by HendX** [comment]
I've just pushed an update which makes this change. Please let me know if this works better for you.

**Comment by edementiev** [comment]
Yes, you are right about versions before 2.4
Your fix correctly working for me, thanks!
