### ISSUE TITLE
Transcription and Comment frame encoding

### ISSUE THREAD

**Issue by NCrusher74** [CrunchyBagel/OutcastID3#5]
I'm having an interesting issue with the Transcription and Comment frames. When I write them using this code:

```swift
            OutcastID3.Frame.CommentFrame(
                encoding: .utf8, language: "eng",
                commentDescription: "description",
                comment: "Comment Test"),
            OutcastID3.Frame.TranscriptionFrame(
                encoding: .utf8, language: "eng",
                lyricsDescription: "description",
                lyrics: "Lyrics Test")
```

And run this test:

``` swift
            // ... test on StringFrame types
            } else if let isolatedFrame = frame as? OutcastID3.Frame.CommentFrame {
                XCTAssertEqual(isolatedFrame.language, "eng")
                XCTAssertEqual(isolatedFrame.commentDescription, "description")
                XCTAssertEqual(isolatedFrame.comment, "Comment Test")
            } else if let isolatedFrame = frame as? OutcastID3.Frame.TranscriptionFrame {
                XCTAssertEqual(isolatedFrame.language, "eng")
                XCTAssertEqual(isolatedFrame.lyricsDescription, "description")
                XCTAssertEqual(isolatedFrame.lyrics, "Lyrics Test")
            }
```

This is the result I see:

<img width="1124" alt="Screen Shot 2020-03-08 at 3 36 22 PM" src="https://user-images.githubusercontent.com/56804260/76172744-0d831e80-6156-11ea-95ea-fa544eeb79c1.png">

And the reason I'm including that as a screenshot is because when I try to cut/paste the test of the error, my posts on GitHub get cut off, because this is the actual text:

<img width="504" alt="Screen Shot 2020-03-08 at 3 44 13 PM" src="https://user-images.githubusercontent.com/56804260/76172754-2d1a4700-6156-11ea-8a13-35d7533e7fb6.png">

and GitHub apparently doesn't like that extra character at the beginning.

I've tried every kind of encoding I can think of and none of them improve the result. And that doesn't explain why the content of the TranscriptionFrame is being written to the CommentFrame.

It also looks like OutcastID3 may be having an issue with adding characters to tags written by other writers. This is what happens when I try to read a file written using `ID3TagEditor` with `OutcastID3`:

``` swift
        for frame in outcastFrames {
            if let isolatedFrame = frame as? OutcastID3.Frame.StringFrame {
                if isolatedFrame.type == AudiobookTag.authors.outcastType {
                    XCTAssertEqual(isolatedFrame.str, "Artist")
                    print((isolatedFrame.str).unicodeScalars.map({ $0.value }))
                    print("Artist".unicodeScalars.map({ $0.value }))
                    }
                }
            }
        let id3TagEditor = ID3TagEditor()
        if let id3Tag = try id3TagEditor.read(from: Bundle.testMp3FullMeta.path) {
            print((id3Tag.frames[.Artist] as? ID3FrameWithStringContent)?.content.unicodeScalars.map({ $0.value }))

        }
```
^^^ this test gets me this result:

```
/OutcastID3Tests.swift:26: error: -[AudiobookTaggerTests.OutcastID3Tests testMP3AudiobookTag] : 
XCTAssertEqual failed: ("Artist[X*]") is not equal to ("Artist")
[65, 114, 116, 105, 115, 116, 0]
[65, 114, 116, 105, 115, 116]
Optional([65, 114, 116, 105, 115, 116])
```
note*: X marks the extra character I removed so that the post wouldn't get cut off.

**Comment by HendX** [comment]
Just to confirm - does your pull request fix this issue?

**Comment by NCrusher74** [comment]
As far as I can tell. I tried it in my own tests and got the right return when used it. It was a simple matter where something was referencing the Transcription frame when it should have said CommentFrame. Probably just an oversight using cut and paste since the code is pretty much identical.

**Comment by NCrusher74** [comment]
That said, you should be aware that your Comment and Transcription frame aren't read properly by any other sources I tried. Your comment frame didn't show up in Comments or anywhere else in Itunes, Yate, Kid3, Fission (and audio editor) or MediaInfo. The transcription frame text appeared properly in Itunes and...I think Fission? But in MediaInfo, it displayed the description string, rather than the content string.

**Comment by NCrusher74** [comment]
Actually, sorry, I misunderstood your question.

No, my pull request didn't fix this particular issue, except for the part about the Comment content string being the Transcription content string.

For this particular issue, I had to find a workaround, which was this:

```swift
        func fixString(string: String) -> String {
            var stringToTrim = string
            stringToTrim.unicodeScalars.removeAll(where: { $0.value < 0x20 })
            return stringToTrim
        }
```
and then call it here:

```swift
               if isolatedFrame.type == AudiobookTag.authors.outcastType {
                    XCTAssertEqual(fixString(stringToFix: isolatedFrame.str), "Author Write Test")
                }
```

Basically, it would add a null character to the end of every frame that wasn't written by OutcastID3 (I checked, the character wasn't there until it was read by Outcast) and it would add a null character (0x00) followed by an "end of text" character (0x03) to the beginning of the Comment and Transcription frames. So removing everything under 0x20 corrected for it.

**Comment by NCrusher74** [comment]
Is there any chance we could work together to fix this? I'm more than willing to help, but I've only been coding for about six months and it's just beyond my skills. However, I have a personal project involving audiobooks I'm working on that requires pretty much all of the most complex of the ID3 frames: Comment, Lyrics, CTOC and CHAP, and finding a framework or library I have the skills to implement into a Swift project is proving to be a nearly impossible task.

The issues I've noted are, as I've said, OutcastID3 appears to be adding a null character to the end of most string frames that it doesn't write, and it appears to write 0x00 and 0x03 at the beginning of the Transcription and Comment frames. I fixed the small error in the Comment frame where it was writing the transcription frame content. I haven't had a chance to test the CTOC and CHAP frames.

My own project is stuck until I find a tool that can do these frames, so I'm very motivated to help, I just don't understand your code well enough to do so.

(also, I'd love to be able to use OutcastID3 as a SPM package instead of a CocoaPod)

**Comment by HendX** [comment]
I'll take a closer look soon, but a bit swamped at the minute. I initially created the library primarily to read chapter info - being able to write out ID3 tags was a secondary thing, but I'd like to have it all working right.

In regards to SPM, I haven't really looked at this yet in general for my own projects, but it's on my todo list.

**Comment by HendX** [comment]
Hi @NCrusher74 - I just committed a fix which addresses the issue.

In fact it looked like there were two separate issues that resulted in each writing the extraneous byte to those frames. Let me know if this works better for you, and if so I'll release to CocoaPods.

**Comment by NCrusher74** [comment]
Thanks, I will put it through its paces and see if it works for me!

**Comment by NCrusher74** [comment]
I created a SPM package of your code and invited you as a collaborator on it. I haven't fully put it through its paces yet, but so far it's working?

**Comment by HendX** [comment]
Ok - I don't have the bandwidth to work on the SPM package currently, but all in good time. Let me know how you go with the other fixes.

**Comment by NCrusher74** [comment]
Well, assuming it works (and so far it does, but I haven't had a chance to fully test it yet) you shouldn't have to do anything. It's yours if you want it.

**Comment by HendX** [comment]
Thanks, appreciate it. I would like to merge it back and release it properly eventually.

**Comment by NCrusher74** [comment]
Yeah I figured. But I figured for now I'd let you know it was there.

I had removed OutcastID3 from my project (with extreme prejudice toward
CocoaPods) so I've had to get things set up again on my end to test it out.
I'm almost there, but so far things are working well.

**Comment by NCrusher74** [comment]
Okay, having run OutcastID through my own reading/writing tests, there are still a couple glitches.

First of all, if the .mp3 file you're writing to doesn't already have an ID3 tag on it, OutcastID3 will error out instead of creating one.

Unbeknownst to me back when I created my metadata-free test file, `ffmpeg` actually strips the ID3 tag off the file rather than just blanking out the values in the frames on the tag. OutcastID3 refuses to have anything to do with that file. I don't know if you intended it to work that way or not, but that's the way it is at present.

Second--and this could be user error--right now Outcast appears to be adding duplicate frames on a file with the frames already written instead of replacing the values in those frames.

<img width="684" alt="Screen Shot 2020-03-17 at 5 34 58 PM" src="https://user-images.githubusercontent.com/56804260/76914340-3783c180-6877-11ea-8670-3f7db9a4d36d.png">
<img width="582" alt="Screen Shot 2020-03-17 at 5 36 31 PM" src="https://user-images.githubusercontent.com/56804260/76914343-3c487580-6877-11ea-86ee-a60873252891.png">

The reason I say this could be user error is because this is how I'm doing it:

```swift
    private var outcastFrames: [OutcastID3TagFrame]?
    
    private mutating func set(_ tag: AudiobookTag, string: String) {
        let stringTags: [AudiobookTag] = [
            .authors,
            .bookTitle,
            .category,
            .copyright,
            .keywords,
            .mediaType,
            .narrators,
            .primaryAuthor,
            .publisher,
            .series,
            .title,
            .universe,
            .genre,
        ]
        if stringTags.contains(tag) {
                    let frame = OutcastID3.Frame.StringFrame(
                        type: tag.outcastType!,
                        encoding: .utf8,
                        str: string)
                    outcastFrames?.append(frame)
        }
    }

```swift
    public mutating func setAuthors(authors: String) throws {
        set(.authors, string: authors)
    }
```

```swift
    //MARK: Write
    public func write(outputUrl: URL) throws {
                 let mp3File = try OutcastID3.MP3File(localUrl: self.audiobookUrl)
                let outcastTag = OutcastID3.ID3Tag(
                    version: .v2_4,
                    frames: outcastFrames ?? [])
                try mp3File.writeID3Tag(tag: outcastTag, outputUrl: outputUrl)
    }
```

So, it could be the fact that the way I'm doing this involves appending to the frame array, but I'm pretty much you want it so that it overwrites instead of appends if there's a value that is supposed to be unique.

**Comment by HendX** [comment]
The library doesn't really do any checking of the frames, so if you have duplicate frames it will write them all.

Also, you need to handle the thrown error if there's no tag and create it accordingly. The library will insert a tag if there isn't one, or replace the tag if there already is one.

**Comment by NCrusher74** [comment]
Well, it's not that I had duplicate frames. It's that the file already had frames and instead of replacing those frames, `OutcastID3` created a new, duplicate frame.

I will see what I can do about handling the situation where the file doesn't have a pre-existing tag. I don't see what option Outcast gives to create a tag if one doesn't already exist aside from simply attempting to write the tag in the first place, but I'll try to see if I can find something.

**Comment by HendX** [comment]
Yea - this is expected behaviour. You need to filter out the old tags you don't want any more before writing back to the file.

Have a look at `MP3File+WriteTag.swift`, around line 82. You can see it removes the existing tag and then replaces it with the new tag.

There are no rules in the library as to what tags can or cannot appear multiple times - it's purely a utility to read/write the tags. You'll still need to manage the specific tags.
